# Generated by Django 6.0.3 on 2026-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.BigIntegerField(db_index=True, unique=True)),
                ('website_summary', models.TextField(blank=True)),
                ('pain_points', models.JSONField(default=list)),
                ('use_cases', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
