# Generated by Django 6.0.3 on 2026-03-20 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title_keywords', models.TextField(blank=True)),
                ('industry_keywords', models.TextField(blank=True)),
                ('search_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_website', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('csv', 'CSV')], default='csv', max_length=32)),
                ('profile_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('researched', 'Researched'), ('emailed', 'Emailed'), ('replied', 'Replied'), ('meeting_booked', 'Meeting booked')], db_index=True, default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.persona')),
            ],
        ),
    ]
